services:
  app:
    build:
      context: .
      args:
        uid: 1000
    container_name: aksamedia_app
    restart: unless-stopped
    ports:
      - "8000:9000"
    volumes:
      - .:/var/www
    networks:
      - sail

  db:
    image: mysql:latest
    container_name: aksamedia_db
    restart: unless-stopped
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - sail

  nginx:
    image: nginx:latest
    container_name: aksamedia_server
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/etc/nginx/conf.d
      - .:/var/www
    depends_on:
      - app
    networks:
      - sail

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: aksamedia_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  db_data:
